- name: Block in file test
  hosts: all
  gather_facts: false
  tasks:
    - name: Block in file Test
      blockinfile:
        path: /etc/nginx/nginx.conf
        insertbefore: '# HSTS'
        marker: ""
        block: |
          location /index.html { alias /usr/share/nginx/html/index/html; }