- name: Block in file test
  hosts: all

  tasks:
    - name: Block in file Test
      blockinfile:
        path: /var/lib/awx/projects/{{ item }}.txt
        insertbefore: BOF
        marker: ""
        block: |
          {{ inventory_hostname }}
          {{ ansible_date_time }}
          {{ item }}
      delegate_to: localhost
        #loop:
      loop:
        - passwd
        - login.defs
        - sudoers