- name: Block in file test
  hosts: all

  tasks:
    - name: Block in file Test
      blockinfile:
        path: /var/lib/awx/projects/{{ item }}.txt
        insertbefore: BOF
        marker: ""
        block: |
          {{inventory_hostname}}
          {{DTE2}}
          {{ item }}
        delegate_to: localhost
        #loop:
      loop:
        - passwd
        - login.defs
        - sudoers