- name: E-mail weblink to user
  hosts: localhost
  gather_facts: no
  connection: local
  
  tasks: 
  - name: Send Web Link via E-mail
    mail:
      host: mail.shadowman.dev
      username: tower@shadowman.dev
      password: IFFJGK6W
      port: 587
      subject: Ansible VM Web Link
      body: "Web address is http://{{ email_ip_address }}/index.html"
      from: tower@shadowman.dev
      to: "{{ to_email }}"
    delegate_to: localhost