- name: Send an e-mail
  hosts: "{{ vm_name }}"
  gather_facts: false
  connection: local
  vars:
    to_email: "{{ to_emails.split(',') }}"
    email_body: "Web address is http://{{ ansible_host }}/index.html"
  
  tasks: 
  - name: Send Web Link via E-mail
    mail:
      host: "{{ EMAIL_HOST }}"
      username: "{{ EMAIL_USERNAME }}"
      password: "{{ EMAIL_PASSWORD }}"
      port: "{{ EMAIL_PORT }}"
      subject: Ansible VM Web Link
      body: "{{ e-mail_body }}"
      from: tower@shadowman.dev
      to: "{{ to_email }}"
    delegate_to: localhost  