- name: Send an e-mail
  hosts: localhost
  gather_facts: no
  connection: local
  
  tasks: 
  - name: Send Web Link via E-mail
    mail:
      host: "{{ EMAIL_HOST }}"
      username: "{{ EMAIL_USERNAME }}"
      password: "{{ EMAIL_PASSWORD }}"
      port: "{{ EMAIL_PORT }}"
      subject: Ansible VM Web Link
      body: "Web address is http://{{ email_ip_address }}/index.html"
      from: tower@shadowman.dev
      to: "{{ to_email }}"
    delegate_to: localhost  