- name: Test file return values
  hosts: all
  gather_facts: no

  tasks: 
  - name : Find files
    find:
      paths: /var/log/tower
      patterns: '*.log'
    register: output
  - name: "Display all cluster names"
    debug:
      var: item
    loop: "{{ output | json_query('files[*].path') }}"
