- name: Test file return values
  hosts: all
  gather_facts: no

  tasks: 
  - name : Find files
    find:
      paths: /var/log/tower
      patterns: '*.log'
    register: output.files

  - debug:
      msg: This is the output {{ output }}