---
- name: Flush Graylog Handlers
  hosts: all
  
  tasks:
  - name: "reload systemd configuration"
    systemd:
      daemon_reload: yes
    ignore_errors: True

  - name: "restart graylog-server"
    service:
      name: "graylog-server"
      state: "restarted"
      enabled: "yes"
    ignore_errors: True

  - name: "restart mongod"
    service:
      name: "mongod"
      state: "restarted"
      enabled: "yes"
    ignore_errors: True