---
- name: Setup graylog
  hosts: all
  vars:
    es_instance_name: "graylog"
    es_scripts: False
    es_templates: False
    es_version_lock: False
    es_heap_size: "1g"
    es_config:
      node.name: "graylog"
      cluster.name: "graylog"
      http.port: 9200
      transport.tcp.port: 9300
      network.host: "127.0.0.1"
      node.data: True
      node.master: True
    graylog_install_java: False # Elasticsearch role already installed Java
    graylog_password_secret: "2jueVqZpwLLjaWxV" # generate with: pwgen -s 96 1
    graylog_root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_http_bind_address: "{{ ansible_host }}:9000"
    graylog_http_publish_uri: "http://{{ ansible_host }}:9000/"
    graylog_http_external_uri: "http://{{ ansible_host }}:9000/"
    graylog_web_endpoint_uri: "http://{{ ansible_host }}:9000/api/"

    nginx_sites:
      graylog:
        - "listen 80"
        - "server_name graylog"
        - |
          location / {
            proxy_pass http://localhost:9000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass_request_headers on;
            proxy_connect_timeout 150;
            proxy_send_timeout 100;
            proxy_read_timeout 100;
            proxy_buffers 4 32k;
            client_max_body_size 8m;
            client_body_buffer_size 128k;
          }

  pre_tasks:

  - name: Install needed packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - https://sat6.shadowman.dev/pub/katello-ca-consumer-latest.noarch.rpm
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    
  - name: Use Activation Key to Register to Satellite
    redhat_subscription:
      state: present
      activationkey: RHEL7 Everything
      org_id: Shadow_Man

  - name: Enable Repositories
    rhsm_repository:
      name: "{{ repos }}"
      purge: True
    vars:
      repos:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-optional-rpms

  - name: Install needed packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - policycoreutils-python

  - name: Open greylog port
    firewalld:
      port: 9000/tcp
      permanent: yes
      state: enabled
    notify: restart_firewalld

  - name: Open greylog port
    firewalld:
      port: 12201/tcp
      permanent: yes
      state: enabled
    notify: restart_firewalld

  roles:
    - role: "Graylog2.graylog-ansible-role"
      tags:
        - "graylog"

  post_tasks:

  - name: Install needed packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - java-1.8.0-openjdk


  handlers:

    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted