---
- name: Flush Graylog Handlers
  hosts: all
  
  tasks:
  - name: "reload systemd configuration"
    systemd:
      daemon_reload: yes
    ignore_errors: True

  - name: "restart graylog-server"
    service:
      name: "graylog-server"
      state: "restarted"
      enabled: "yes"
    ignore_errors: True

  - name: "restart mongod"
    service:
      name: "mongod"
      state: "restarted"
      enabled: "yes"
    ignore_errors: True

  - name: "SELinux port access should be granted for graylog-server"
    seport:
      ports: 9000
      proto: "tcp"
      setype: "mongod_port_t"
      state: "present"
    ignore_errors: True