- name: Block in file test
  hosts: all
  tasks:
    
    - name: Line in file add
      lineinfile:
        path: /var/lib/awx/projects/{{ item }}.txt
        insertbefore: BOF
        firstmatch: yes
        create: yes
        line: '{{ inventory_hostname }} {{ ansible_date_time.date }} {{ item }}'
      loop:
        - passwd
        - login.defs
        - sudoers