- name: Check OS version
  hosts: all
  tasks: 
    - name: Check OS version
      debug:  
        msg: "Host: {{ inventory_hostname }}, is running {{ ansible_distribution }} {{ ansible_distribution_version }}" 
   
