- name: Run Python Script
  hosts: all
  gather_facts: false

  tasks: 
    - name: Run script
      script: Simple.py 
      args:
        executable: python
      register: result

    - name: Print result to screen
      debug:
        var: result   