---
- name: Remove VM on RHV
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      tags:
        - always
  vars:
    datacenter: Default
    vm_names: "{{ vm_name.split(',') }}"

  tasks:
    - name: Stop VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ item }}"
        state: stopped
        wait: yes
      loop: "{{ vm_names }}"

    - name: Delete VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ item }}"
        state: absent
        wait: yes
      loop: "{{ vm_names }}"

  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always