- name: Create an incident in ServiceNow
  hosts: all
  gather_facts: no
  connection: local
  
  tasks: 
  - name: Create an incident in ServiceNow
    snow_record:
      username: '{{ lookup("env", "SN_USERNAME") }}'
      password: '{{ lookup("env", "SN_PASSWORD") }}'
      instance: '{{ lookup("env", "SN_INSTANCE") }}'
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 3
        priority: 2
    register: new_incident