- name: Create an incident in ServiceNow
  hosts: all
  gather_facts: no
  connection: local
  
  tasks: 
  - name: Create an incident in ServiceNow
    snow_record:
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 2
        priority: 2
        u_operating_system: "{{ ansible_lsb.description }}"
        u_ip_address: "{{ ansible_eth0.ipv4.address }}"
    register: new_incident

  - debug: 
      var: new_incident.record