- name: Create an incident in ServiceNow
  hosts: all
  gather_facts: no
  connection: local
  
  tasks: 
  - name: Create an incident in ServiceNow
    snow_record:
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 2
        priority: 2
    register: new_incident

  - debug: 
      var: new_incident.record