- name: Create an incident in ServiceNow
  hosts: all
  gather_facts: yes
  connection: local
  
  tasks: 
  - name: Create an incident in ServiceNow
    snow_record:
      state: present
      data:
        short_description: "{{ incident_description }}"
        caller_id: "System Administrator"
        urgency: "{{ sn_urgency }}"
        impact: "{{ sn_impact }}"
        u_operating_system: "{{ ansible_lsb.description }}"
        u_ip_address: "{{ ansible_default_ipv4.address }}"
    register: new_incident

  - debug: 
      var: new_incident.record.number