---
- name: Update VM on RHV using Terraform
  hosts: all
  gather_facts: false

  vars:
    - vm_names: "{{ vm_name.split(,) }}"
  
  tasks:
    - name: Update terraform main file
      template: 
        src: terraform.tf.j2
        dest: ~/terraform/ovirt/main.tf
        
    - name: Update State of VM to {{ terraform_state }} from template using Terraform
      terraform:
        project_path: "~/terraform/ovirt/"
        state: "{{ terraform_state }}"
        force_init: yes