---
- name: Wait for host to generate IP
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"

  tasks:

    - name: Check stats of VM name
      ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: name={{ vm_name }}
      register: result
      until:  result.ovirt_vms[0].guest_operating_system.kernel.version.build is defined
      retries: 30
      delay: 10

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"