---
- name: Wait for host to generate IP
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: sleep for 120 seconds and continue with play
      wait_for:
        timeout: 120
      delegate_to: localhost