- name: Install nginx, insert an index page, verify service is started and that the index page works
  hosts: all

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: Check that you can connect to the index page and that Hello is in the contents
    uri:
      url: https://192.168.56.100/index.html
      validate_certs: no
      return_content: yes
    register: this
    failed_when: "'Hello' not in this.content"
