- name: Install nginx, insert an index page, verify service is started and that the index page works
  hosts: "{{ new_host }}"

  tasks:

  - name: Add apache
    yum:
      name: httpd
      state: latest
    notify: httpd_running

  - name: Insert Index Page for webpage
    template:
      src: index.html.j2
      dest: /var/www/html/index.html

  - name: Check that you can connect to the index page and that Hello is in the contents
    uri:
      url: https://{{ ansible_default_ipv4.address }}/index.html
      validate_certs: no
      return_content: yes
    register: this
    failed_when: "'Hello' not in this.content"

  handlers:
    - name: httpd_running
      service:
        name: httpd
        state: started