- name: Install apache, insert an index page, verify service is started and that the index page works
  hosts: "{{ new_host }}"

  tasks:
  - name: Install Katello RPM for Satellite Server
    yum:
      name: https://sat6.shadowman.dev/pub/katello-ca-consumer-latest.noarch.rpm
      state: present

  - name: Use Activation Key to Register to Satellite
    redhat_subscription:
      state: present
      activationkey: RHEL7 Everything
      org_id: Shadow_Man

  - name: Enable Repositories
    rhsm_repository:
      name: "{{ repos }}"
      purge: True
    vars:
      repos:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-optional-rpms
        
  - name: Open Firewalld for apache
    firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: Open Firewalld for SSL
    firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: Add apache package
    yum:
      name: httpd
      state: latest
    notify: httpd_running

  - name: Insert Index Page for webpage
    template:
      src: index.html.j2
      dest: /var/www/html/index.html

  post_tasks:
  - name: Check that you can connect to the index page and that Hello is in the contents
    uri:
      url: https://{{ ansible_default_ipv4.address }}/index.html
      validate_certs: no
      return_content: yes
    register: this
    failed_when: "'Hello' not in this.content"

  handlers:
    - name: httpd_running
      service:
        name: httpd
        state: started
