- name: Install apache, insert an index page, verify service is started and that the index page works
  hosts: "{{ vm_name }}"
  gather_facts: false
  tasks:
        
  - name: Open Firewalld for apache
    firewalld:
      service: http
      permanent: yes
      state: enabled
    notify: restart_firewalld

  - name: Open Firewalld for SSL
    firewalld:
      service: https
      permanent: yes
      state: enabled
    notify: restart_firewalld

  - name: Add apache package
    yum:
      name: httpd
      state: latest
    notify: httpd_running
  
  - name: Insert webpage formatting for html
    copy:
      src: website/
      dest: /var/www/html/

  - name: Insert Index Page for webpage
    template:
      src: templates/indexcomplex.html.j2
      dest: /var/www/html/index.html

  post_tasks:
  - name: Check that you can connect to the index page and that Hello is in the contents
    uri:
      url: http://{{ ansible_host }}/index.html
      validate_certs: no
      return_content: yes
    register: this
    failed_when: "'Alex Dworjan' not in this.content"

  - name: Print web address
    debug: 
      msg: "Web address is http://{{ ansible_host }}/index.html"

  - name: Set facts for the e-mail body
    set_fact:
      email_body: "Web address is http://{{ ansible_host }}/index.html"
      email_subject: "Ansible VM Web Link"

  handlers:
    - name: httpd_running
      service:
        name: httpd
        state: started

    - name: restart_firewalld
      service:
        name: firewalld
        state: restarted
