- name: Test
  hosts: all
  gather_facts: false
  tasks: 
    - name: Debug
      debug:  
        msg: "The current user is {{ ansible_user }}"

    - name: Ping Test
      ping:

    - name: yum test
      yum:
        name: wget
        state: present
          